In [1]:
import pandas as pd

In [2]:
#creating dataframe
data = {
    "Name": ["Jaya", "Rahul", "Priya", "Amit"],
    "Marks": [85, 92, 78, 88],
    "Attendance": [90, 95, 88, 91]
}

df = pd.DataFrame(data)

df

    Name  Marks  Attendance
0   Jaya     85          90
1  Rahul     92          95
2  Priya     78          88
3   Amit     88          91

In [6]:
#basic information
print (df.shape)
print (df.columns)
print (df.dtypes)

#statistics
df.describe()

(4, 3)
Index(['Name', 'Marks', 'Attendance'], dtype='object')
Name          object
Marks          int64
Attendance     int64
dtype: object

           Marks  Attendance
count   4.000000     4.00000
mean   85.750000    91.00000
std     5.909033     2.94392
min    78.000000    88.00000
25%    83.250000    89.50000
50%    86.500000    90.50000
75%    89.000000    92.00000
max    92.000000    95.00000

In [8]:
#sorting
df.sort_values("Marks", ascending=False)

    Name  Marks  Attendance
1  Rahul     92          95
3   Amit     88          91
0   Jaya     85          90
2  Priya     78          88

In [9]:
#filtering
high_scorers = df[df["Marks"] > 80]

high_scorers

    Name  Marks  Attendance
0   Jaya     85          90
1  Rahul     92          95
3   Amit     88          91

In [10]:
#create new column
df["Result"] = df["Marks"] >= 80

df

    Name  Marks  Attendance  Result
0   Jaya     85          90    True
1  Rahul     92          95    True
2  Priya     78          88   False
3   Amit     88          91    True

In [11]:
print("Average Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

Average Marks: 85.75
Highest Marks: 92
Lowest Marks: 78

In [14]:
#lambda function
df["Performance"] = df["Marks"].apply(
    lambda x: "Excellent" if x >= 90
    else "Good" if x >= 80
    else "Average"
)

df

    Name  Marks  Attendance  Result Performance
0   Jaya     85          90    True        Good
1  Rahul     92          95    True   Excellent
2  Priya     78          88   False     Average
3   Amit     88          91    True        Good